### PR TITLE
Added simulated data for UI testing

### PR DESCRIPTION
**Pull request by noelpaz**
Pkt Data is being populated with values that would have come
from the sensors. Uncomment //#define SET_VALUES when testing

### CODE REVIEW

**Comment by noelpaz** [comment]
@mrrosen can we merge this to develop ASAP. It's in ifdef clause. Needed for testing

**Comment by zmk5** [comment]
Can you fix it real quick? I also don't think you need their permission to merge it.

**Comment by mrrosen** [comment]
@noelpaz We are targeting develop to be ready-to-go on the device itself, so I rather have extra steps for people wanting to do validation test (ie, defining additional macros) than for people wanting to flash a final device. So, I was just say to anyone wanting to do testing on bare boards to uncomment the macros than for people trying to flash actual built ventilators to define/undefine macros.

**Comment by noelpaz** [comment]
@mrrosen  Those changes were helpful for figuring out the flow with the UI and we found bugs because we have that.  The testing team are also able to write test cases because of it. Not sure why we cannot merge t.  It is not going to be compiled in unless the #define is uncommented

**Comment by mrrosen** [comment]
@noelpaz I didnt notice that you had included a number of new fields sorry; but please fix it so that #define is commented out and the code compiles.

**Comment by noelpaz** [comment]
We will just rebase to develop - so we are always in sync and provide this for the validation team until they have access to proper HW

**Comment by mrrosen** [comment]
Great, thanks for fixing it

**Pull request merged**
