### PR TITLE
Add License Header

### PR DESCRIPTION
**Pull request by ilakshmank**
added license header to all files

### CODE REVIEW

**Comment by mrrosen** [comment]
Should add it to software-controller.ino in the main directory as well.

Also, it would be better if you added new lines in the header so the lines arent so long, at 80/100 char is typical

**Comment by ilakshmank** [comment]
Ok. Will make the changes

**Comment by ilakshmank** [comment]
Done and committed,

**Comment by mrrosen** [comment]
Looks good, been added since its just really one commit (the top one), I just added that commit to develop so this is done now

**Pull request closed without merging**
